### ISSUE TITLE
Position still appears in the list in positionOverview even though it has been deleted

### ISSUE THREAD

**Issue by TMink** [TMink/Digitales-3D-Feldbuch#234]
After a position has been deleted and you are back in the placeOverview, the position is still displayed in the list. A reload fixes the whole thing.

Use-Case:
Create activity -> create place -> create position -> save position -> delete position => Still in the list

**Comment by JuHardtung** [comment]
I can't seem to reproduce this. Is this still an issue on your end?
![cantReproduce](https://github.com/TMink/Digitales-3D-Feldbuch-Projekt-3-/assets/15029310/459cfbda-bf51-4b00-a70d-c4f01095054d)
